// typescript/m5/sales_assistant/tools/html.ts
/**
 * Render the weekly newsletter Markdown into a styled, sanitized HTML page.
 *
 * Belongs to the main agent. The HTML shell is a fixed, trusted template; the
 * newsletter body is derived from untrusted web-search text, so it is run
 * through an allowlist sanitizer (sanitize-html) before it goes into the
 * page — stripping any <script>, onerror=, etc. that a search result might
 * have smuggled in.
 */
import { marked } from "marked";
import sanitizeHtml from "sanitize-html";
import { z } from "zod";
import { context, tool } from "langchain";

const HTML_TEMPLATE = (title: string, body: string) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${title}</title>
<style>
  body { max-width: 760px; margin: 40px auto; padding: 0 20px;
          font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
          line-height: 1.6; color: #1a1a1a; }
  h1 { font-size: 2rem; border-bottom: 3px solid #006DDD; padding-bottom: .3em; }
  h2 { color: #006DDD; margin-top: 1.6em; }
  footer { margin-top: 3em; color: #777; font-size: .85rem;
            border-top: 1px solid #ddd; padding-top: 1em; }
</style>
</head>
<body>
${body}
<footer>Generated by the Chinook Sales Assistant.</footer>
</body>
</html>`;

export const markdownToHtml = tool(
  async ({ markdownText, title }: { markdownText: string; title: string }) => {
    let body = (await marked.parse(markdownText)) as string;
    // The body is built from untrusted web search, so allowlist-sanitize it
    // before rendering. The template itself is trusted and left intact.
    body = sanitizeHtml(body);
    return HTML_TEMPLATE(title, body);
  },
  {
    name: "markdown_to_html",
    description: context`
      Convert a Markdown newsletter into a complete, styled HTML page.
      Returns the full HTML document as a string.`,
    schema: z.object({
      markdownText: z.string(),
      title: z.string().default("This Week in Music"),
    }),
  }
);
