// typescript/m4/m4_2_newsletter_agent.ts
/**
 * Module 4 · Lesson 2 — Building a subagent team.
 *
 * An "editor" main agent delegates each of the distributor's top music genres to
 * a single `genre-researcher` subagent type, run in parallel. Each researcher
 * web-searches its genre, keeps the raw results in an assigned /research/<genre>/
 * scratch folder, and returns one short article segment. The editor assembles the
 * segments and writes a styled HTML newsletter to /output/newsletter.html.
 *
 * The agent runs on the default (ephemeral) StateBackend — it never touches the
 * real local filesystem. The companion m4.2_run_newsletter.ts extracts the finished HTML from agent state
 * and writes it to disk.
 */

import { z } from "zod";
import { marked } from "marked";
import sanitizeHtml from "sanitize-html";

import { context, tool } from "langchain";
import {
  createDeepAgent,
  type FilesystemPermission,
  type SubAgent,
} from "deepagents";
import { TavilySearchAPIWrapper } from "@langchain/tavily";

import { model, strongModel } from "../models.js";

// The distributor's top genres — known up front, no database needed.
const TOP_GENRES = ["Rock", "Latin", "Metal", "Alternative & Punk"];

// --- Tools -----------------------------------------------------------------
// internetSearch belongs ONLY to the subagent (see `tools:` below).
const tavilyApiKey = process.env.TAVILY_API_KEY;
if (!tavilyApiKey) {
  throw new Error(
    "TAVILY_API_KEY is required for the Module 4.2 newsletter lab. " +
    "Set it in your environment before running m4.2_run_newsletter.ts."
  );
}

const tavily = new TavilySearchAPIWrapper({ tavilyApiKey });

const internetSearch = tool(
  async ({ query, maxResults }: { query: string; maxResults: number }) => {
    return tavily.rawResults({ query, max_results: maxResults, topic: "news" });
  },
  {
    name: "internet_search",
    description: context`
      Search the web for recent news. Use this to research what's new in a
      music genre — new releases, notable artists, trends, and events.`,
    schema: z.object({
      query: z.string(),
      maxResults: z.number().default(8),
    }),
  }
);

// markdownToHtml belongs ONLY to the editor (the main agent).
// The template is a fixed, static string. NOTE: in production you would
// sanitize model/search-derived text before rendering it to HTML.
const HTML_TEMPLATE = (title: string, body: string) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${title}</title>
<style>
  body { max-width: 760px; margin: 40px auto; padding: 0 20px;
          font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
          line-height: 1.6; color: #1a1a1a; }
  h1 { font-size: 2rem; border-bottom: 3px solid #006DDD; padding-bottom: .3em; }
  h2 { color: #006DDD; margin-top: 1.6em; }
  footer { margin-top: 3em; color: #777; font-size: .85rem;
            border-top: 1px solid #ddd; padding-top: 1em; }
</style>
</head>
<body>
${body}
<footer>Generated by a Deep Agents subagent team.</footer>
</body>
</html>`;

const markdownToHtml = tool(
  async ({ markdownText, title }: { markdownText: string; title: string }) => {
    let body = (await marked.parse(markdownText)) as string;
    // Good practice: the newsletter text is derived from untrusted web search,
    // so allowlist-sanitize it (strips <script>, onerror=, etc.) before it goes
    // into the page. We clean only the body; the template itself is trusted.
    body = sanitizeHtml(body);
    return HTML_TEMPLATE(title, body);
  },
  {
    name: "markdown_to_html",
    description: context`
      Convert a Markdown newsletter into a complete, styled HTML page.
      Returns the full HTML document as a string.`,
    schema: z.object({
      markdownText: z.string(),
      title: z.string().default("This Week in Music"),
    }),
  }
);

// --- The research subagent -------------------------------------------------
const GENRE_PROMPT = context`
  You are a music journalist researching one genre for an
  online music distributor's weekly newsletter.

  You will be given a single genre and an assigned research folder to work in.

  How to work:
  1. Use internet_search to find recent, noteworthy developments in that genre
     — new releases, notable artists, trends, or events. Run a few searches.
  2. Save the COMPLETE, verbatim output of ALL your searches to a single file:
     write_file("/research/<genre>/sources.md", ...). Paste the results exactly
     as the tool returned them — every result's title, URL, and full content
     snippet. Do NOT summarize, trim, or reformat. This one file is your raw
     archive: all the bulky material stays here so it never clutters the
     editor's context.
  3. Only then, from what you found, write one tight newsletter segment.

  Return ONLY the finished segment as your reply:
  - A markdown section: a "## <Genre>" heading followed by ~120-180 words.
  - Lively but factual newsletter tone; name specific artists and releases.
  - Do NOT paste raw search results or link dumps into your reply — those live
    in your research files. Return just the polished segment.`;

// Researchers may write under /research/** and are denied writes elsewhere.
const researchPermissions: FilesystemPermission[] = [
  { operations: ["read", "write"], paths: ["/research/**"], mode: "allow" },
  { operations: ["write"], paths: ["/**"], mode: "deny" },
];

const genreResearcher: SubAgent = {
  name: "genre-researcher",
  description: context`
    Research one music genre and write a short newsletter segment about
    what's new in it. Delegate one genre per call.`,
  systemPrompt: GENRE_PROMPT, // its own brain — never inherited
  tools: [internetSearch], // override — replaces the inherited set
  model, // override — the cheaper Haiku 4.5
  permissions: researchPermissions, // override — scoped write access
};

// --- The editor (main agent) -----------------------------------------------
const EDITOR_PROMPT = context`
  You are the editor of an online music distributor's weekly
  newsletter. This week you are featuring the distributor's top genres:
  ${TOP_GENRES.join(", ")}.

  Your job:
  1. For EACH genre, delegate to the genre-researcher subagent using the task
     tool — fire them off in parallel. Tell each one which genre to cover and
     which assigned folder to use (/research/<genre>/), and ask for one segment.
  2. Collect the four returned segments. Do NOT research genres yourself.
  3. Assemble them into one Markdown newsletter: a top-level "# This Week in
     Music" title, a one-sentence intro, then the four "## <Genre>" sections.
  4. Call markdown_to_html on the assembled Markdown, then write_file the
     returned HTML to /output/newsletter.html.

  Keep your own context focused on coordination and assembly.`;

// The editor uses the stronger shared model; the researcher overrides to the
// cheaper `model` (Haiku 4.5) above. Both come from models.ts.

// The editor may read the research area but must not write into it.
const editorPermissions: FilesystemPermission[] = [
  { operations: ["write"], paths: ["/research/**"], mode: "deny" },
];

export const agent = createDeepAgent({
  model: strongModel,
  tools: [markdownToHtml],
  systemPrompt: EDITOR_PROMPT,
  subagents: [genreResearcher],
  permissions: editorPermissions,
});
